using Hjson; // ← 使用你已导入的 Hjson 插件
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public class GenerateL10nKeysFromHjson {
    // 🔧 配置区 —— 根据你的项目调整
    private const string FilePath = "StreamingAssets/Localization/zh-CN.hjson"; // 相对于 Assets/
    private const string OutputPath = "JoG/Localization/L10nKeys.cs";
    private const string Namespace = "JoG.Localization";

    [MenuItem("Tools/Localization/Generate L10nKeys from Hjson")]
    public static void Generate() {
        string hjsonFullPath = Path.Combine(Application.dataPath, FilePath);
        if (!File.Exists(hjsonFullPath)) {
            Debug.LogError($"❌ Hjson file not found: {hjsonFullPath}");
            return;
        }

        try {
            var root = HjsonValue.Load(hjsonFullPath); // ✅ 使用 Hjson 解析器
            if (root.JsonType != JsonType.Object) {
                Debug.LogError("Root of Hjson must be an object.");
                return;
            }
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Generated from: " + FilePath);
            sb.AppendLine("// DO NOT EDIT MANUALLY");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class L10nKeys");
            sb.AppendLine("    {");

            BuildClassFromHjson(root as JsonObject, "", sb, 2);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string outputFullPath = Path.Combine(Application.dataPath, OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(outputFullPath));
            File.WriteAllText(outputFullPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            Debug.Log($"✅ L10nKeys generated successfully!\n→ {outputFullPath}");
        } catch (System.Exception ex) {
            Debug.LogError($"❌ Failed to generate L10nKeys: {ex.Message}\n{ex.StackTrace}");
        }
    }

    private static void BuildClassFromHjson(JsonObject obj, string currentPath, StringBuilder sb, int indentLevel) {
        var indent = new string(' ', indentLevel * 4);

        foreach (var kvp in obj) {
            string key = kvp.Key;
            JsonValue value = kvp.Value;
            string newPath = string.IsNullOrEmpty(currentPath) ? key : $"{currentPath}.{key}";

            if (value.JsonType == JsonType.String) {
                string fieldName = ToPascalCase(key);
                sb.AppendLine($"{indent}public const string {fieldName} = \"{newPath}\";");
            } else if (value.JsonType == JsonType.Object) {
                string className = ToPascalCase(key);
                sb.AppendLine($"{indent}public static class {className}");
                sb.AppendLine($"{indent}{{");
                BuildClassFromHjson(value as JsonObject, newPath, sb, indentLevel + 1);
                sb.AppendLine($"{indent}}}");
            }
            // 忽略 Array / Number / Boolean 等（本地化表通常只用字符串）
        }
    }

    // 辅助：将任意命名风格转为 PascalCase
    private static string ToPascalCase(string input) {
        if (string.IsNullOrEmpty(input)) return "Empty";

        // 支持: bootstrap_loading → BootstrapLoading
        //       bootstrap-loading → BootstrapLoading
        //       bootstrap.loading → BootstrapLoading
        input = input.Replace('-', '_').Replace('.', '_');
        string[] parts = input.Split('_', System.StringSplitOptions.RemoveEmptyEntries);
        for (int i = 0; i < parts.Length; i++) {
            string part = parts[i];
            parts[i] = char.ToUpper(part[0]) + (part.Length > 1 ? part[1..].ToLower() : "");
        }
        return string.Join("", parts);
    }
}