// <auto-generated />
// Generated from: StreamingAssets/Localization/zh-CN.hjson
// DO NOT EDIT MANUALLY

namespace JoG.Localization
{
    public static partial class L10nKeys
    {
        public const string Language = "language";
        public static class Buff
        {
            public static class Bleeding
            {
                public const string Name = "buff.bleeding.name";
                public const string Desc = "buff.bleeding.desc";
            }
            public static class Poison
            {
                public const string Name = "buff.poison.name";
                public const string Desc = "buff.poison.desc";
            }
            public static class Burning
            {
                public const string Name = "buff.burning.name";
                public const string Desc = "buff.burning.desc";
            }
            public static class Frost
            {
                public const string Name = "buff.frost.name";
                public const string Desc = "buff.frost.desc";
            }
            public static class Curse
            {
                public const string Name = "buff.curse.name";
                public const string Desc = "buff.curse.desc";
            }
            public static class DemonicMight
            {
                public const string Name = "buff.demonic_might.name";
                public const string Desc = "buff.demonic_might.desc";
            }
            public static class Healing
            {
                public const string Name = "buff.healing.name";
                public const string Desc = "buff.healing.desc";
            }
        }
        public static class Item
        {
            public static class CursedWand
            {
                public const string Name = "item.cursed_wand.name";
                public const string Desc = "item.cursed_wand.desc";
            }
            public static class DefenseShield
            {
                public const string Name = "item.defense_shield.name";
                public const string Desc = "item.defense_shield.desc";
            }
            public static class FlameStaff
            {
                public const string Name = "item.flame_staff.name";
                public const string Desc = "item.flame_staff.desc";
            }
            public static class FrostStaff
            {
                public const string Name = "item.frost_staff.name";
                public const string Desc = "item.frost_staff.desc";
            }
            public static class HealthPotion
            {
                public const string Name = "item.health_potion.name";
                public const string Desc = "item.health_potion.desc";
            }
            public static class Medkit
            {
                public const string Name = "item.medkit.name";
                public const string Desc = "item.medkit.desc";
            }
            public static class PoisonBottle
            {
                public const string Name = "item.poison_bottle.name";
                public const string Desc = "item.poison_bottle.desc";
            }
            public static class VampiricScythe
            {
                public const string Name = "item.vampiric_scythe.name";
                public const string Desc = "item.vampiric_scythe.desc";
            }
            public static class HolyCore
            {
                public const string Name = "item.holy_core.name";
                public const string Desc = "item.holy_core.desc";
            }
            public static class HolySword
            {
                public const string Name = "item.holy_sword.name";
                public const string Desc = "item.holy_sword.desc";
            }
            public static class HolyStar
            {
                public const string Name = "item.holy_star.name";
                public const string Desc = "item.holy_star.desc";
            }
            public static class Thornmail
            {
                public const string Name = "item.thornmail.name";
                public const string Desc = "item.thornmail.desc";
            }
            public static class CrimsonPendant
            {
                public const string Name = "item.crimson_pendant.name";
                public const string Desc = "item.crimson_pendant.desc";
            }
        }
        public static class Interact
        {
            public static class Status
            {
                public const string Active = "interact.status.active";
                public const string Inactive = "interact.status.inactive";
            }
            public static class DemonAltar
            {
                public const string Name = "interact.demon_altar.name";
                public const string Desc = "interact.demon_altar.desc";
            }
            public static class HolyAltar
            {
                public const string Name = "interact.holy_altar.name";
                public const string Desc = "interact.holy_altar.desc";
            }
            public static class AudioPlayer
            {
                public const string Name = "interact.audio_player.name";
                public const string Desc = "interact.audio_player.desc";
            }
            public static class VideoPlayer
            {
                public const string Name = "interact.video_player.name";
                public const string Desc = "interact.video_player.desc";
            }
            public static class Teleporter
            {
                public const string Name = "interact.teleporter.name";
                public const string Desc = "interact.teleporter.desc";
            }
            public static class GameEndRock
            {
                public const string Name = "interact.game_end_rock.name";
                public const string Desc = "interact.game_end_rock.desc";
            }
        }
        public static class Character
        {
            public static class Fighter
            {
                public const string Name = "character.fighter.name";
                public const string Desc = "character.fighter.desc";
            }
            public static class Ghost
            {
                public const string Name = "character.ghost.name";
                public const string Desc = "character.ghost.desc";
            }
            public static class Mage
            {
                public const string Name = "character.mage.name";
                public const string Desc = "character.mage.desc";
            }
            public static class Skeleton
            {
                public const string Name = "character.skeleton.name";
                public const string Desc = "character.skeleton.desc";
            }
            public static class Spitter
            {
                public const string Name = "character.spitter.name";
                public const string Desc = "character.spitter.desc";
            }
            public static class Golem
            {
                public const string Name = "character.golem.name";
                public const string Desc = "character.golem.desc";
            }
            public static class GiantDummy
            {
                public const string Name = "character.giant_dummy.name";
                public const string Desc = "character.giant_dummy.desc";
            }
        }
        public static class Objective
        {
            public const string Header = "objective.header";
            public const string KillObjective = "objective.kill_objective";
            public const string KillBossObjective = "objective.kill_boss_objective";
            public const string TimerObjective = "objective.timer_objective";
            public const string EndObjective = "objective.end_objective";
        }
        public static class UnityServices
        {
            public const string InitFailed = "unity_services.init_failed";
        }
        public static class Session
        {
            public const string Title = "session.title";
            public static class Name
            {
                public const string Label = "session.name.label";
                public const string Placeholder = "session.name.placeholder";
            }
            public static class Password
            {
                public const string Label = "session.password.label";
                public const string Placeholder = "session.password.placeholder";
            }
            public static class MaxPlayers
            {
                public const string Label = "session.max_players.label";
                public const string Placeholder = "session.max_players.placeholder";
            }
            public static class IsPrivate
            {
                public const string Label = "session.is_private.label";
            }
            public static class Code
            {
                public const string Label = "session.code.label";
                public const string Placeholder = "session.code.placeholder";
            }
            public static class List
            {
                public const string Title = "session.list.title";
            }
            public static class Create
            {
                public const string Title = "session.create.title";
                public const string Button = "session.create.button";
                public const string DefaultName = "session.create.default_name";
                public const string Created = "session.create.created";
                public const string Failed = "session.create.failed";
            }
            public static class Join
            {
                public const string Title = "session.join.title";
                public const string Button = "session.join.button";
                public const string Joined = "session.join.joined";
                public const string Failed = "session.join.failed";
            }
            public static class Query
            {
                public const string Title = "session.query.title";
                public static class Filter
                {
                    public const string Title = "session.query.filter.title";
                }
                public static class Refresh
                {
                    public const string Button = "session.query.refresh.button";
                }
            }
        }
        public static class Settings
        {
            public static class Network
            {
                public static class NetworkSmoothing
                {
                    public const string Label = "settings.network.network_smoothing.label";
                    public const string Tooltip = "settings.network.network_smoothing.tooltip";
                }
            }
            public static class General
            {
                public const string Title = "settings.general.title";
                public const string Language = "settings.general.language";
                public static class FullScreenMode
                {
                    public const string Label = "settings.general.full_screen_mode.label";
                    public const string ExclusiveFullScreen = "settings.general.full_screen_mode.exclusive_full_screen";
                    public const string FullScreenWindow = "settings.general.full_screen_mode.full_screen_window";
                    public const string MaximizedWindow = "settings.general.full_screen_mode.maximized_window";
                    public const string Windowed = "settings.general.full_screen_mode.windowed";
                }
            }
            public static class Graphic
            {
                public const string Title = "settings.graphic.title";
                public static class QualityLevel
                {
                    public const string Label = "settings.graphic.quality_level.label";
                    public const string Low = "settings.graphic.quality_level.low";
                    public const string Medium = "settings.graphic.quality_level.medium";
                    public const string High = "settings.graphic.quality_level.high";
                }
            }
            public static class Audio
            {
                public const string Title = "settings.audio.title";
                public const string MainVolume = "settings.audio.main_volume";
                public const string MusicVolume = "settings.audio.music_volume";
                public const string EffectVolume = "settings.audio.effect_volume";
            }
        }
        public static class Mods
        {
            public const string Title = "mods.title";
            public static class ListHeader
            {
                public const string ModName = "mods.list_header.mod_name";
                public const string ModAuthor = "mods.list_header.mod_author";
                public const string ModDesc = "mods.list_header.mod_desc";
                public const string ModVersion = "mods.list_header.mod_version";
                public const string ModEnabled = "mods.list_header.mod_enabled";
            }
        }
        public static class MainMenu
        {
            public static class Introduce
            {
                public const string Button = "main_menu.introduce.button";
            }
            public static class Multiplayer
            {
                public const string Button = "main_menu.multiplayer.button";
            }
            public static class Mods
            {
                public const string Button = "main_menu.mods.button";
            }
            public static class Settings
            {
                public const string Button = "main_menu.settings.button";
            }
            public static class Quit
            {
                public const string Button = "main_menu.quit.button";
                public const string Message = "main_menu.quit.message";
            }
        }
        public static class IngameMenu
        {
            public const string Title = "ingame_menu.title";
            public static class Resume
            {
                public const string Button = "ingame_menu.resume.button";
            }
            public static class Settings
            {
                public const string Button = "ingame_menu.settings.button";
            }
            public static class Disconnect
            {
                public const string Button = "ingame_menu.disconnect.button";
                public const string Message = "ingame_menu.disconnect.message";
            }
            public static class Quit
            {
                public const string Button = "ingame_menu.quit.button";
                public const string Message = "ingame_menu.quit.message";
            }
            public static class Respawn
            {
                public const string Button = "ingame_menu.respawn.button";
            }
        }
        public static class Popup
        {
            public static class Confirm
            {
                public const string Button = "popup.confirm.button";
            }
            public static class Cancel
            {
                public const string Button = "popup.cancel.button";
            }
        }
        public static class Profile
        {
            public static class Name
            {
                public const string Label = "profile.name.label";
                public const string Placeholder = "profile.name.placeholder";
                public static class Error
                {
                    public const string EmptyOrWhitespace = "profile.name.error.empty_or_whitespace";
                    public const string TooShort = "profile.name.error.too_short";
                    public const string TooLong = "profile.name.error.too_long";
                    public const string InvalidCharacters = "profile.name.error.invalid_characters";
                    public const string NoValidLetters = "profile.name.error.no_valid_letters";
                }
            }
        }
    }
}
